name: Publish

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build plugin
        run: npm run build
      - name: Zip output
        run: |
          cd dist
          zip -r ../plugin.zip *
          cd ..
      - name: Upload release asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./plugin.zip
          asset_name: plugin.zip
          asset_content_type: application/zip
